server:
  port: 8080

spring:
  application:
    name: commodeami-service
  datasource:
    url: jdbc:mariadb://localhost:3306/commodeamidb
    driver-class-name: org.mariadb.jdbc.Driver
    username: siuuuuu
    password: siuuuuu
  jpa:
    hibernate:
#      ddl-auto: update

    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
logging:
  level:
    com:
      siuuuuu_o3o:
        commodeami: DEBUG #로깅 레벨 설정

tmdb:
  api:
    key: 9550e567632ee9cb94d888507db51c5f
    url: https://api.themoviedb.org/3/movie

kobis:
  api:
    key: 98d803dc53cb34137673132c300efa0c
    url: http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json
