server:
  port: 8080

spring:
  application:
    name: commodeami-service
  datasource:
    url: jdbc:mariadb://localhost:3306/commodeamidb
    driver-class-name: org.mariadb.jdbc.Driver
    username: siuuuuu
    password: siuuuuu
  jpa:
    hibernate:
#      ddl-auto: update

    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
logging:
  level:
    com:
      siuuuuu:
        commodeami: DEBUG #로깅 레벨 설정

app:
  cors:
    allowed-origins: http://localhost:5173
  frontend-url: http://localhost:8080

springdoc:
  swagger-ui:
    # swagger-ui ?? ??. default ?? /swagger-ui.html??.
    path: /swagger-custom-ui.html

    # ? API? ?? ?? ??
    # path, query, body, response ??? ??
    groups-order: DESC

    # ?? ?? ??.
    # alpha: ??? ? ??
    # method: OpenAPI specification file? ??? ?? ?? ?? ?? ??
    tags-sorter: alpha

    # ???? ?? ??.
    # method? delete - get - patch - post - put ??? ????.
    # alpha? ??? ??? ??? ??? ? ??.
    operations-sorter: method

    # swagger-ui default url? petstore html? ???? ??
    disable-swagger-default-url: true

    # swagger-ui?? try ?? ? request duration? ???? ??
    display-request-duration: true

  # Spring Actuator? endpoint?? ??? ????
  show-actuator: true

  # request media type ? ?? ?
  default-consumes-media-type: application/json

  # response media type ? ?? ?
  default-produces-media-type: application/json

token:
  access-expiration-time: 3600000
  refresh-expiration-time: 86400000
  secret: Y8xQHdbBkWXO8hEiDNEKxbgtnWlhBVw+q2/djGQMnzgXMCzOkSqDGaFhdL8iNrdKKncyQt/xDXbF2rR/k8Re/Q==

tmdb:
  api:
    key: 9550e567632ee9cb94d888507db51c5f
    url: https://api.themoviedb.org/3/movie

kobis:
  api:
    key: 98d803dc53cb34137673132c300efa0c
    url: http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json
